spring.application.name=firststudyProject
server.port=${PORT:8080}



spring.jpa.hibernate.ddl-auto=none

#
#spring.datasource.url=${DATABASE_URL}
#spring.datasource.username=${DATABASE_USERNAME}
#spring.datasource.password=${DATABASE_PASSWORD}
#spring.security.user.name=${SWAGGER_USERNAME}
#spring.security.user.password=${SWAGGER_PASSWORD}

spring.datasource.url=jdbc:postgresql://db.slwuqkexpmwhifdykomw.supabase.co:5432/postgres?user=postgres
spring.datasource.username= postgres
spring.datasource.password=ingtW3fw8cBvXVbl

spring.security.user.name=CryPmin@436AMShar
spring.security.user.password=$2a$10$3qMjV2Aw6FwZGNSZnDwqZ.74tBgv9sGVy2zHR/CNlQp0rlfZWMdyW

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

