spring.application.name=firststudyProject
server.port=${PORT:8080}

#db details 

#spring.datasource.url=${DATABASE_URL}
#spring.datasource.username=${DATABASE_USERNAME}
#spring.datasource.password=${DATABASE_PASSWORD}
#spring.security.user.name=${SWAGGER_USERNAME}
#spring.security.user.password=${SWAGGER_PASSWORD}
spring.jpa.hibernate.ddl-auto=none


# HikariCP — optimized for Supabase

spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.idle-timeout=180000
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-timeout=30000

# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.connection.handling_mode=DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION

#Critical for Supabase PgBouncer
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#actuator for health
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

